### ISSUE TITLE
Prematurely finishing a trip crashes app.

### ISSUE THREAD

**Issue by b0wter** [b0wter/ETA#81]
No final SMS is sent!

**Comment by b0wter** [comment]
Seems to only happen after the app is running for some time.

Sample stack trace:
`Uncaught exception: 
Invalid destinationAddress 
java.lang.IllegalArgumentException: Invalid destinationAddress
at android.telephony.SmsManager.sendTextMessageInternal(SmsManager.java:309)
at android.telephony.SmsManager.sendTextMessage(SmsManager.java:301)
at de.roughriders.jf.eta.activities.TripActivity$6.onClick(TripActivity.java:294)
at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:157)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6121)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)`

**Comment by b0wter** [comment]
Issue could not be recreated.
